// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxNvJ8mutjvifWEztc1CM63x7L_ziJRnU',
    appId: '1:697651562718:web:0b07f38424fde2fe971a4f',
    messagingSenderId: '697651562718',
    projectId: 'room1-4e6b4',
    authDomain: 'room1-4e6b4.firebaseapp.com',
    databaseURL: 'https://room1-4e6b4-default-rtdb.firebaseio.com',
    storageBucket: 'room1-4e6b4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfEdbgijmq2BOAqsEtrLnuu0IP3sLhQVI',
    appId: '1:697651562718:android:4a3567c6278781dc971a4f',
    messagingSenderId: '697651562718',
    projectId: 'room1-4e6b4',
    databaseURL: 'https://room1-4e6b4-default-rtdb.firebaseio.com',
    storageBucket: 'room1-4e6b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4dqoAWlySElg0BGy32F1yhk1ClVwhUM8',
    appId: '1:697651562718:ios:479d27505c1ca18c971a4f',
    messagingSenderId: '697651562718',
    projectId: 'room1-4e6b4',
    databaseURL: 'https://room1-4e6b4-default-rtdb.firebaseio.com',
    storageBucket: 'room1-4e6b4.firebasestorage.app',
    iosBundleId: 'com.example.onepay',
  );
}
